name: Build Sphinx user documentation

# Controls when the action will run. 
on:
  # Triggers the workflow on push only for the master branch
  push:
    branches: [ master ]

jobs:
  build_sphinx_documentation:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checking-out repository
      - uses: actions/checkout@v2
  
      - name: Building Sphinx documentation from source files
      - uses: ammaraskar/sphinx-action@0.4
        with:
          docs-folder: "docs/user/"
          build-command: "sphinx-build -b html source build"
  
      - name: Zipping and uploading HTML static files as an artifact
      - uses: actions/upload-artifact@v1
        with:
          name: FLO2D_QGIS_Plugin_Documentation
          path: docs/user/build/

      - name: Commit documentation changes
        run: |
          git clone https://github.com/ammaraskar/sphinx-action-test.git --branch gh-pages --single-branch gh-pages
          cp -r docs/user/build/* gh-pages/
          cd gh-pages
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Update documentation" -a || true
          # The above command will fail if no changes were present, so we ignore
          # the return code.
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          branch: gh-pages
          directory: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force: true

