name: Build and publish user documentation

# Controls when the action will run. 
on:
  # Triggers the workflow on push only for the master branch
  push:
    branches: [ master ]

jobs:
  build_sphinx_documentation:
    name: Building Sphinx documentation and uploading as an artifact
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        name: Checking-out repository
  
      - uses: ammaraskar/sphinx-action@0.4
        name: Building Sphinx documentation from source files
        with:
          docs-folder: "docs/user/"
          build-command: "sphinx-build -b html source build"
  
      - uses: actions/upload-artifact@v1
        name: Zipping and uploading HTML static files as an artifact
        with:
          name: FLO2D_QGIS_Plugin_Documentation
          path: docs/user/build/

  publish_user_documentation:
      name: Publishing user documentation
      needs: [build_sphinx_documentation]
      runs-on: ubuntu-latest
      steps:
      - uses: actions/download-artifact@v2
        with:
          name: FLO2D_QGIS_Plugin_Documentation
          path: docs/user/build/

      - name: Commiting documentation changes
        run: |
          git clone https://github.com/ammaraskar/sphinx-action-test.git --branch gh-pages --single-branch gh-pages
          cp -r docs/user/build/* gh-pages/
          cd gh-pages
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Update documentation" -a || true
          # The above command will fail if no changes were present, so we ignore
          # the return code.
  
      - name: Pushing changes on GitHub Pages branch
        uses: ad-m/github-push-action@master
        with:
          branch: gh-pages
          directory: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force: true
